version: '3'

services:
  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      - users-service
    links:
      - users-service

  db:
    container_name: db
    build: ./server/db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  users-service:
    container_name: users-service
    build: ./
    volumes:
            - '.:/usr/src/app'
    ports:
            - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
            - APP_SETTINGS=server.config.DevelopmentConfig
            - DATABASE_URL=mysql://root:root@db:3306/users_dev
            - DATABASE_TEST_URL=mysql://root:root@db:3306/users_test
    depends_on:
            - db

  web-service:
    container_name: web-service
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/usr/src/app'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
